[aliases.class]
"Microsoft-edge" = "Edge"
"code-oss" = "Code"
"Clash.*" = "Clash"
"kitty" = "Kitty"
"com.alibabainc.dingtalk" = "DingTalk"
"org.wezfurlong.wezterm" = "Wezterm"
"dev.warp.Warp" = "Warp"
"firefox*" = "Firefox"
"dev.zed.Zed" = "Zed"

[aliases.name]
".*Writer.*" = "Word"
".*Spreadsheets.*" = "Excel"
".*Presentation.*" = "Slides"
"MATLAB.*" = "Matlab"
"Wolfram.*" = "Mathematica"

[icons]
Edge = ""
Firefox = ""
Thunar = ""
Kitty = ""
Wezterm = ""
Warp = ""
KeePassXC = ""
obsidian = "󰺿"
Word = ""
Excel = ""
Slides = ""
Code = ""
Zed = ""
Clash = "󰲀"
Zotero = ""
okular = ""
Zeal = ""
DingTalk = ""
Matlab = ""
Mathematica = ""
wechat = ""

[general]
default_icon = ""
split_at = ":"
empty_label = "🌕"
display_property = "instance"

[options]
remove_duplicates = true
no_names = false
no_icon_names = false
