[aliases.class]
"Microsoft-edge" = "Edge"
"code-oss" = "Code"
"Clash*" = "Clash"

[icons]
Edge = ""
Thunar = ""
kitty = ""
KeePassXC = ""
obsidian = "󰺿"
wps = ""
Code = ""
Clash = "󰲀"
Zotero = ""
okular = ""
Zeal = ""

[general]
default_icon = ""
split_at = ":"
empty_label = "🌕"
display_property = "instance"

[options]
remove_duplicates = true
no_names = false
no_icon_names = false
