[aliases.class]
"Microsoft-edge" = "Edge"
"code-oss" = "Code"
"Clash.*" = "Clash"
"kitty" = "Kitty"
"com.alibabainc.dingtalk" = "DingTalk"
"org.wezfurlong.wezterm" = "Wezterm"
"firefox*" = "Firefox"
"dev.zed.Zed" = "Zed"
"dev.warp.Warp" = "Warp"
"strawberry" = "Music"
"com.github.johnfactotum.Foliate" = "Reader"
"libreoffice-writer" = "Writer"
"libreoffice-calc" = "Excel"
"libreoffice-impress" = "Slides"
"libreoffice-startcenter" = "Office"

[aliases.name]
".*Writer.*" = "Word"
".*Spreadsheets.*" = "Excel"
".*Presentation.*" = "Slides"
"MATLAB.*" = "Matlab"
"Wolfram.*" = "Mathematica"

[icons]
Edge = ""
Chromium = ""
Firefox = ""
Thunar = ""
Kitty = ""
Wezterm = ""
Warp = ""
XPipe = ""
KeePassXC = ""
obsidian = "󰺿"
Word = "󰈭"
Excel = "󰈜"
Slides = "󰈨"
Office = "󰈭"
Cursor = "󰅨"
Code = "󰅨"
Zed = "󰅨"
Clash = "󰲀"
Zotero = ""
okular = "󰈦"
Zeal = ""
DingTalk = ""
Matlab = ""
Mathematica = ""
wechat = ""
Music = ""
Reader = ""
"LM Studio" = ""
CherryStudio = ""

[general]
separator = "  "
split_at = ":"
empty_label = "🆓"
display_property = "instance"
default_icon = ""

[options]
remove_duplicates = true
no_names = false
no_icon_names = false
