[aliases.class]
"Microsoft-edge" = "Edge"
"code-oss" = "Code"
"Clash.*" = "Clash"
"com.alibabainc.dingtalk" = "DingTalk"

[aliases.name]
".*Writer.*" = "Word"
".*Spreadsheets.*" = "Excel"
".*Presentation.*" = "Slides"

[icons]
Edge = ""
Thunar = ""
kitty = ""
KeePassXC = ""
obsidian = "󰺿"
Word = ""
Excel = ""
Slides = ""
Code = ""
Clash = "󰲀"
Zotero = ""
okular = ""
Zeal = ""
DingTalk = ""

[general]
default_icon = ""
split_at = ":"
empty_label = "🌕"
display_property = "instance"

[options]
remove_duplicates = true
no_names = false
no_icon_names = false
