[aliases.class]
"Microsoft-edge" = "Edge"
"code-oss" = "Code"
"Clash.*" = "Clash"
"kitty" = "Kitty"
"com.alibabainc.dingtalk" = "DingTalk"
"org.wezfurlong.wezterm" = "Wezterm"
"firefox*" = "Firefox"
"dev.zed.Zed" = "Zed"
"strawberry" = "Music"
"com.github.johnfactotum.Foliate" = "Reader"
"libreoffice-writer" = "Writer"
"libreoffice-calc" = "Excel"
"libreoffice-impress" = "Slides"
"libreoffice-startcenter" = "Office"

[aliases.name]
".*Writer.*" = "Word"
".*Spreadsheets.*" = "Excel"
".*Presentation.*" = "Slides"
"MATLAB.*" = "Matlab"
"Wolfram.*" = "Mathematica"

[icons]
Edge = ""
Firefox = ""
Thunar = ""
Kitty = ""
Wezterm = ""
XPipe = ""
KeePassXC = ""
obsidian = "󰺿"
Word = ""
Excel = ""
Slides = ""
Office = ""
Cursor = ""
Code = ""
Zed = ""
Clash = "󰲀"
Zotero = ""
okular = ""
Zeal = ""
DingTalk = ""
Matlab = ""
Mathematica = ""
wechat = ""
Music = ""
Reader = ""

[general]
separator = "  "
split_at = ":"
empty_label = "🆓"
display_property = "instance"
default_icon = ""

[options]
remove_duplicates = true
no_names = false
no_icon_names = false
