[theme]
theme = "gruvbox-dark"

[icons]
icons = "material-nf"

[[block]]
block = "battery"
format = "$icon $percentage "
missing_format = ""

[[block]]
block = "net"
format = " $icon {$signal_strength $ssid|Wired connection} $ip"

[[block]]
block = "sound"

[[block]]
block = "time"
format = "$icon $timestamp.datetime() "
interval = 60

[[block]]
block = "pomodoro"
notify_cmd = "notify-send '{msg}'"
blocking_cmd = false
